### ISSUE TITLE
rebble-auth and rebble-boot need to interact

### ISSUE THREAD

**Issue by jwise** [pebble-dev/rebble-auth-py#3]
The boot server needs to deliver customized URLs to tell RWS apps about what session they're associated with, because RWS apps might not always get a token passed (for instance, dictation is token-less).  As such, we need the following changes:

* rebble-boot needs to be customized to take a token in its URL, and generate boot JSON blobs that have the token baked in to each element.
* rebble-auth needs to take the token, also.  Its behavior is the same, in general, but it doesn't inform the mobile app that it's happy until the boot JSON token matches the token for the logged in account.  If the boot JSON token is incorrect, it emits a pebble:// link that redirects to a new boot blob.

We solve this, in general, by adding a new URL element.  All RWS Pebble.apk-facing (or Pebble.ipa-facing) URLs have, as their first path two path tokens, `/mobile/<token>`, followed by the rest of their URL (so, perhaps, `/mobile/<token>/oauth/authorize`).  This avoids the issue in which only the prefix of a URL is specified (and, as such, we cannot reasonably append a token in a query-string), but adds the problem of having to add a new route for each handler.  We solve this by using a [URL processor](http://flask.pocoo.org/docs/0.12/patterns/urlprocessors/), with the app itself wrapped in a blueprint that is capable of stripping `/mobile/<token>` off the front.

**Comment by jwise** [comment]
We discussed this some on Discord, and after having a look at the boot config, it looks like the app doesn't construct any unusual paths -- so we should be able to get away with appending a query string, `?token=<token>`.  This will be a little more difficult for dictation -- we'll need a special token ID for that.  We can come back to that one later.  Instead, the proposed changes are now:

* Customize rebble-boot as described above.
* Customize rebble-auth as described above, but instead of prepending a `/mobile/<token>` path element, we append a `?token=<token>` querystring.

**Comment by Katharine** [comment]
Some further questions:

- how do we get the token into the boot URL in the first place? That might be a place where passing `access_token=foo` doesn't work due to the Android app's behaviour of appending to the path. I don't know if it's smart enough to append in the right place if there's a query string. (conversely, the information it appends is not very interesting, and we could just add an `&` and then ignore what it's appending).
- What do we want the login webview presented to actually _do_? In particular, you say "…until the boot JSON token matches the token for the logged in account" — we can't perform real auth in the webview because our auth providers won't let us embed them in a webview. I was thinking we might just use it to inform the user of who they are logging in as and let them confirm that intent, but if we're concerned about security we could go better and do something like having them enter a number that we show them in a real browser elsewhere.

Also, I recommend using `access_token` as the query param name because that's fairly standard.

**Comment by jwise** [comment]
I think my plan for the boot URL was going to in fact be to have that in path -- the boot path then being `https://boot.rebble.io/<token>` instead of `https://boot.rebble.io`.

The login webview, I had originally planned to have a 'numbers matching' approach -- you'd do something as follows:
* go to `login.rebble.io` from a real computer or from a phone browser
* log in
* hit the 'log in from phone' button
* on your phone, attempt to log in; you get a challenge number
* enter the challenge number on your desktop, get a response number
* enter the response number on your phone
* the auth webview on the phone irritatedly says "hey, you're using the wrong boot JSON", and redirects you to a pebble:// link with the right one

This has the problem that the flow for doing this kind of sucks if you're on a phone -- and it sucks a lot if you're on a low-memory phone that barely can hold a browser and the Pebble UI in view at the same time.  Inconveniently, in 2018, nobody uses desktops any more, and everybody only has a phone, because the evolution of computing is consumption, not creation, so we probably need to optimize for phones.  Instead, I propose (as, I think, you suggested on Discord) that the boot server in fact _never_ uses the login webview, I suppose; and as a result, the boot JSON has tokens baked in, and is only ever set to a custom JSON (there is no "generic boot JSON") -- the only way to get a boot JSON is for authing from a real on-phone browser to provide you with one through a `pebble://` link.

So I think I only propose changes to `rebble-boot` as above, and `rebble-auth` does not need to grow any endpoints at all, other than whatever it would take to hand `rebble-boot` an appropriate token.
